-define(CONDITION_TRIGGER_START_OF_OWN_ATTACK, soowa).
-define(CONDITION_TRIGGER_START_OF_OTHER_ATTACK, soota).
-define(CONDITION_TRIGGER_START_OF_ANY_ATTACK, soana).

-define(CONDITION_TRIGGER_END_OF_OWN_ATTACK, eoowa).
-define(CONDITION_TRIGGER_END_OF_OTHER_ATTACK, eoota).
-define(CONDITION_TRIGGER_END_OF_ANY_ATTACK, eoana).

-define(CONDITION_TRIGGER_COMPUTED_OWN_ATTACK_DAMAGE, cowad).
-define(CONDITION_TRIGGER_COMPUTED_OTHER_ATTACK_DAMAGE, cotad).
-define(CONDITION_TRIGGER_COMPUTED_ANY_ATTACK_DAMAGE, canad).

-define(CONDITION_TRIGGER_END_OF_OWN_HIT, eoowh).
-define(CONDITION_TRIGGER_END_OF_OTHER_HIT, eooth).
-define(CONDITION_TRIGGER_END_OF_ANY_HIT, eoanh).

-define(CONDITION_TRIGGER_ROLLED_FOR_OWN_CRITICAL_HITS, rfowch).
-define(CONDITION_TRIGGER_ROLLED_FOR_OTHER_CRITICAL_HITS, rfotch).
-define(CONDITION_TRIGGER_ROLLED_FOR_ANY_CRITICAL_HITS, rfanch).

-define(CONDITION_TRIGGER_ROLLED_FOR_OWN_PRECISION, rfowpr).
-define(CONDITION_TRIGGER_ROLLED_FOR_OTHER_PRECISION, rfotpr).
-define(CONDITION_TRIGGER_ROLLED_FOR_ANY_PRECISION, rfanpr).

-define(CONDITION_TRIGGER_ROLLED_FOR_OWN_PARRY, rfowpa).
-define(CONDITION_TRIGGER_ROLLED_FOR_OTHER_PARRY, rfotpa).
-define(CONDITION_TRIGGER_ROLLED_FOR_ANY_PARRY, rfanpa).

-define(CONDITION_TRIGGER_ROLLED_FOR_OWN_DOUBLE_HITS, rfowdh).
-define(CONDITION_TRIGGER_ROLLED_FOR_OTHER_DOUBLE_HITS, rfotdh).
-define(CONDITION_TRIGGER_ROLLED_FOR_ANY_DOUBLE_HITS, rfandh).

-define(CONDITION_TRIGGER_DEFINED_ACTORS_FOR_OWN_HIT, dafowh).
-define(CONDITION_TRIGGER_DEFINED_ACTORS_FOR_OTHER_HIT, dafoth).
-define(CONDITION_TRIGGER_DEFINED_ACTORS_FOR_ANY_HIT, dafanh).

-define(CONDITION_TRIGGER_MAY_HAVE_BEEN_KILLED, mhbk).
-define(CONDITION_TRIGGER_MAY_HAVE_KILLED, mhk).
-define(CONDITION_TRIGGER_ANY_POSSIBLE_KILL, pk).
-define(CONDITION_TRIGGER_HAS_DIED, hd).

-define(CONDITION_TRIGGER_PLAYER_DEFEAT, pd).
-define(CONDITION_TRIGGER_A_CHARACTER_HAS_DIED, achd).

-define(CONDITION_TRIGGER_ABOUT_TO_MOVE, atm).
-define(CONDITION_TRIGGER_A_CHARACTER_IS_ABOUT_TO_MOVE, aciatm).

-define(CONDITION_TRIGGER_HAS_MOVED, hm).
-define(CONDITION_TRIGGER_A_CHARACTER_HAS_MOVED, achm).

-define(CONDITION_TRIGGER_ABOUT_TO_SWITCH_WEAPONS, atsw).
-define(CONDITION_TRIGGER_A_CHARACTER_IS_ABOUT_TO_SWITCH_WEAPONS, aciatsw).

-define(CONDITION_TRIGGER_HAS_SWITCHED_WEAPONS, hsw).
-define(CONDITION_TRIGGER_A_CHARACTER_HAS_SWITCHED_WEAPONS, achsw).

-define(CONDITION_TRIGGER_ABOUT_TO_USE_THEIR_SKILL, atcs).
-define(CONDITION_TRIGGER_A_CHARACTER_IS_ABOUT_TO_USE_THEIR_SKILL, aciatcs).

-define(CONDITION_TRIGGER_HAS_USED_THEIR_SKILL, hcs).
-define(CONDITION_TRIGGER_A_CHARACTER_HAS_USED_THEIR_SKILL, achcs).
