-define(CONDITION_TRIGGER_START_OF_OWN_ATTACK, soowa).
-define(CONDITION_TRIGGER_START_OF_OTHER_ATTACK, soota).

-define(CONDITION_TRIGGER_END_OF_OWN_ATTACK, eoowa).
-define(CONDITION_TRIGGER_END_OF_OTHER_ATTACK, eoota).

-define(CONDITION_TRIGGER_COMPUTED_OWN_ATTACK_DAMAGE, cowad).
-define(CONDITION_TRIGGER_COMPUTER_OTHER_ATTACK_DAMAGE, cotad).

-define(CONDITION_TRIGGER_END_OF_OWN_HIT, eoowh).
-define(CONDITION_TRIGGER_END_OF_OTHER_HIT, eooth).

-define(CONDITION_TRIGGER_ROLLED_FOR_OWN_CRITICAL_HITS, rfowch).
-define(CONDITION_TRIGGER_ROLLED_FOR_OTHER_CRITICAL_HITS, rfotch).

-define(CONDITION_TRIGGER_ROLLED_FOR_OWN_PRECISION, rfowpr).
-define(CONDITION_TRIGGER_ROLLED_FOR_OTHER_PRECISION, rfotpr).

-define(CONDITION_TRIGGER_ROLLED_FOR_OWN_PARRY, rfowpa).
-define(CONDITION_TRIGGER_ROLLED_FOR_OTHER_PARRY, rfotpa).

-define(CONDITION_TRIGGER_ROLLED_FOR_OWN_DOUBLE_HITS, rfowdh).
-define(CONDITION_TRIGGER_ROLLED_FOR_OTHER_DOUBLE_HITS, rfotdh).

-define(CONDITION_TRIGGER_DEFINED_ACTORS_FOR_OWN_HIT, dafowh).
-define(CONDITION_TRIGGER_DEFINED_ACTORS_FOR_OTHER_HIT, dafoth).
